# Generated by Django 4.1.13 on 2025-02-15 10:31

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication_Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('thumbnail_link', models.CharField(max_length=300)),
                ('video_link', models.CharField(max_length=300, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_id', to='Authentication_Service.userdetails')),
            ],
            options={
                'db_table': 'Reels',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('image_link', models.CharField(max_length=300, null=True)),
                ('thumbnail_link', models.CharField(max_length=300)),
                ('video_link', models.CharField(max_length=300, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader_id', to='Authentication_Service.userdetails')),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
