# Generated by Django 4.1.13 on 2025-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming_Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumbnail_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
