# Generated by Django 4.1.13 on 2025-02-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming_Service', '0003_posts_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='gif_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
