# Generated by Django 4.1.13 on 2025-02-14 12:54

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.TextField()),
                ('phone_no', models.CharField(max_length=20)),
                ('profile_picture', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.CharField(choices=[('PR', 'PRIVATE'), ('PB', 'PUBLIC')], default='PB', max_length=2)),
                ('wallet_id', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'User_Details_Table',
            },
        ),
    ]
